name: Build Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: 'https://test_value.com'
      DATABASE_URL_NON_POOLING: 'https://test_value.com'
      NEXTAUTH_SECRET: 'https://test_value.com'
      GITHUB_CLIENT_ID: 'https://test_value.com'
      GITHUB_CLIENT_SECRET: 'https://test_value.com'
      TMDB_API_KEY: 'https://test_value.com'
      REDIS_URL: 'https://test_value.com'
      NEXTAUTH_URL: 'https://test_value.com'
     
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Run tests
        run: npm run test:ci

      - name: Call Vercel Deploy Hook
        env:
          DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST $DEPLOY_HOOK_URL
